name: alquran
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_lazy_indexed_stack: ^0.0.6
  gap: ^3.0.1
  get: ^4.6.6
  http: ^1.2.2
  lottie: ^3.1.3
  get_storage: ^2.1.1
  just_audio: ^0.9.43
  sqflite: ^2.3.3+1
  path_provider: ^2.1.5
  path: ^1.9.0
  skeletonizer: ^1.4.3

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/lotties/
    - assets/images/
